// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIUvHW6066bY00p0W6ParwIWBWPqyFQo',
    appId: '1:727578316563:web:a82070e6177023339254e6',
    messagingSenderId: '727578316563',
    projectId: 'sargent-yaml',
    authDomain: 'sargent-yaml.firebaseapp.com',
    storageBucket: 'sargent-yaml.firebasestorage.app',
    measurementId: 'G-68CYCH0TL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbMgOp3QM0sBiHqjt25fRIRq5gmFlyPE',
    appId: '1:727578316563:android:6451e8463b8eeec19254e6',
    messagingSenderId: '727578316563',
    projectId: 'sargent-yaml',
    storageBucket: 'sargent-yaml.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdKK7Kafhmbf0rJku3mK1LXnJxUnhkFvM',
    appId: '1:727578316563:ios:ca24c9bc09f5b76c9254e6',
    messagingSenderId: '727578316563',
    projectId: 'sargent-yaml',
    storageBucket: 'sargent-yaml.firebasestorage.app',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdKK7Kafhmbf0rJku3mK1LXnJxUnhkFvM',
    appId: '1:727578316563:ios:ca24c9bc09f5b76c9254e6',
    messagingSenderId: '727578316563',
    projectId: 'sargent-yaml',
    storageBucket: 'sargent-yaml.firebasestorage.app',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsIUvHW6066bY00p0W6ParwIWBWPqyFQo',
    appId: '1:727578316563:web:3a501540938a8cfa9254e6',
    messagingSenderId: '727578316563',
    projectId: 'sargent-yaml',
    authDomain: 'sargent-yaml.firebaseapp.com',
    storageBucket: 'sargent-yaml.firebasestorage.app',
    measurementId: 'G-BPNWCZ9TER',
  );
}
